name: Course first workflow
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello Mary!"
      - name: print goodbay
        run: echo "Bye Mary!"
